"use client";

import React, { useState } from "react";
import { useAuth } from "@/context/AuthContext";
import Image from "next/image";

// Define the structure for the API response
interface GenerationResult {
  message: string;
  imageId: string;
  imageUrl: string;
}

interface SelectedImage {
  imageId: string;
  prompt: string;
  imageUrl: string;
  timestamp: string;
  s3Key: string;
}

interface MainGeneratorPanelProps {
  selectedImage?: SelectedImage | null;
  onImageGenerated?: () => void;
}

export default function MainGeneratorPanel({
  selectedImage,
  onImageGenerated,
}: MainGeneratorPanelProps) {
  const { isAuthenticated, isLoading } = useAuth();
  const [prompt, setPrompt] = useState("");
  const [currentImage, setCurrentImage] = useState<GenerationResult | null>(
    null
  );
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState("");
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [imageStyle, setImageStyle] = useState("none");
  const [imageDimensions, setImageDimensions] = useState("1024x1024");
  const [currentS3Key, setCurrentS3Key] = useState<string | null>(null);

  // Download image function
  const handleDownloadImage = async () => {
    if (!currentImage?.imageUrl) return;

    try {
      const response = await fetch(currentImage.imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `ziagen-${prompt
        .substring(0, 30)
        .replace(/[^a-z0-9]/gi, "-")}-${Date.now()}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Error downloading image:", error);
      alert("Failed to download image. Please try again.");
    }
  };

  // Update prompt and image when a gallery image is selected
  React.useEffect(() => {
    if (selectedImage) {
      setPrompt(selectedImage.prompt);
      setCurrentImage({
        message: "Image from gallery",
        imageId: selectedImage.imageId,
        imageUrl: selectedImage.imageUrl,
      });
      setCurrentS3Key(selectedImage.s3Key);
      setIsRegenerating(true);
    }
  }, [selectedImage]);

  // Function to call free Hugging Face model via local API route
  const handleGenerateImage = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!isAuthenticated) {
      setError("You must be signed in to generate images.");
      return;
    }

    if (!prompt) {
      setError("Please enter a prompt.");
      return;
    }

    setIsGenerating(true);
    setError("");
    setCurrentImage(null);

    try {
      const response = await fetch("/api/generate-hf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt,
          style: imageStyle,
          dimensions: imageDimensions,
          s3Key: isRegenerating ? currentS3Key : null,
        }),
      });

      if (!response.ok) {
        const data = await response.json().catch(() => ({}));
        throw new Error(
          data.error ||
            data.message ||
            `Request failed: ${response.status} ${response.statusText}`
        );
      }

      const data = (await response.json()) as { imageUrl?: string };
      if (!data.imageUrl) {
        throw new Error("No image returned from the model.");
      }

      const imageUrl = data.imageUrl;
      const id = (
        crypto.randomUUID
          ? crypto.randomUUID()
          : `${Date.now()}-${Math.random()}`
      ) as string;

      setCurrentImage({
        message: "Generated by Hugging Face",
        imageId: id,
        imageUrl,
      });
      setIsRegenerating(false);

      if (onImageGenerated) {
        onImageGenerated();
      }
    } catch (error: unknown) {
      console.error("❌ Hugging Face Error:", error);
      const message =
        error instanceof Error
          ? error.message
          : typeof error === "string"
          ? error
          : "Image generation failed. Check console.";
      setError(message);
    } finally {
      setIsGenerating(false);
    }
  };

  if (isLoading) {
    // Show a simplified loading state while AuthContext initializes
    return (
      <div className="flex justify-center items-center h-full text-white">
        Loading Application...
      </div>
    );
  }

  if (!isAuthenticated) {
    return (
      <div className="flex justify-center items-center h-full">
        <div className="p-8 bg-gray-800 rounded-lg shadow-xl text-white text-center">
          <h2 className="text-2xl font-bold mb-4">Access Denied</h2>
          <p className="mb-6">Please sign in to start generating AI images.</p>
        </div>
      </div>
    );
  }

  // Authenticated user view

  return (
    <div className="flex flex-col h-full p-4 sm:p-6 md:p-8 bg-gray-900 overflow-hidden">
      <h1 className="text-2xl sm:text-3xl font-bold text-white mb-4 sm:mb-6 shrink-0">
        Create New Image
      </h1>

      {/* Prompt Input Form */}
      <form onSubmit={handleGenerateImage} className="mb-4 sm:mb-6 shrink-0">
        {isRegenerating && (
          <div className="mb-3">
            <button
              type="button"
              onClick={() => {
                setCurrentImage(null);
                setPrompt("");
                setError("");
                setIsRegenerating(false);
                setCurrentS3Key(null);
              }}
              className="px-4 py-2 rounded-lg font-semibold transition-all text-sm bg-gray-600 hover:bg-gray-700 active:bg-gray-800 text-white cursor-pointer flex items-center gap-2"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M10 19l-7-7m0 0l7-7m-7 7h18"
                />
              </svg>
              Create New Image
            </button>
          </div>
        )}

        {/* Style and Dimension Selectors */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-3">
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1">
              Image Style
            </label>
            <select
              value={imageStyle}
              onChange={(e) => setImageStyle(e.target.value)}
              className="w-full p-2 sm:p-3 rounded-lg bg-gray-700 text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 text-sm sm:text-base cursor-pointer"
            >
              <option value="none">Default</option>
              <option value="ghibli">Studio Ghibli / Anime</option>
              <option value="cartoon">Cartoon / Comic</option>
              <option value="pixel">Pixel Art</option>
              <option value="realistic">Realistic / Photorealistic</option>
              <option value="oil">Oil Painting</option>
              <option value="watercolor">Watercolor</option>
              <option value="digital">Digital Art</option>
              <option value="cyberpunk">Cyberpunk</option>
              <option value="fantasy">Fantasy Art</option>
              <option value="minimalist">Minimalist</option>
              <option value="3d">3D Render</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1">
              Image Dimensions
            </label>
            <select
              value={imageDimensions}
              onChange={(e) => setImageDimensions(e.target.value)}
              className="w-full p-2 sm:p-3 rounded-lg bg-gray-700 text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 text-sm sm:text-base cursor-pointer"
            >
              <option value="512x512">Square - 512×512</option>
              <option value="768x768">Square - 768×768</option>
              <option value="1024x1024">Square - 1024×1024 (Default)</option>
              <option value="512x768">Portrait - 512×768</option>
              <option value="768x1024">Portrait - 768×1024</option>
              <option value="768x512">Landscape - 768×512</option>
              <option value="1024x768">Landscape - 1024×768</option>
              <option value="1024x512">Wide - 1024×512</option>
            </select>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row gap-2 sm:gap-4">
          <input
            type="text"
            placeholder="Enter your prompt here..."
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            disabled={isGenerating}
            className="grow p-2 sm:p-3 rounded-lg bg-gray-700 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm sm:text-base"
          />
          <button
            type="submit"
            disabled={isGenerating || !prompt}
            className={`px-4 sm:px-6 py-2 sm:py-3 rounded-lg font-semibold transition-all text-sm sm:text-base whitespace-nowrap ${
              isGenerating
                ? "bg-gray-400 dark:bg-gray-500 text-gray-200 dark:text-gray-300 cursor-not-allowed"
                : isRegenerating
                ? "bg-orange-600 hover:bg-orange-700 active:bg-orange-800 text-white cursor-pointer"
                : "bg-green-600 hover:bg-green-700 active:bg-green-800 text-white cursor-pointer"
            }`}
          >
            {isGenerating
              ? "Generating..."
              : isRegenerating
              ? "Regenerate"
              : "Generate"}
          </button>
        </div>
        {error && (
          <p className="text-red-500 mt-2 text-sm sm:text-base">{error}</p>
        )}
      </form>

      {/* Image Display Area */}
      <div className="flex-1 bg-gray-800 rounded-lg flex items-center justify-center overflow-hidden min-h-0 p-0 relative">
        {isGenerating ? (
          <div className="text-blue-400 text-sm sm:text-base md:text-lg flex flex-col sm:flex-row items-center gap-2 sm:gap-0 px-4 text-center">
            <svg
              className="animate-spin h-5 w-5 sm:h-5 sm:w-5 md:-ml-1 md:mr-3 text-blue-400"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                className="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
              ></circle>
              <path
                className="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
              ></path>
            </svg>
            <span className="sm:ml-0">
              Please wait, Your requested image is being generated... (30s max)
            </span>
          </div>
        ) : currentImage?.imageUrl ? (
          <>
            <Image
              src={currentImage.imageUrl}
              alt={`Generated image for: ${prompt}`}
              fill
              className="object-contain rounded-md shadow-2xl"
              sizes="100vw"
            />
            {/* Download Button */}
            <button
              onClick={handleDownloadImage}
              className="absolute top-4 right-4 bg-green-600 hover:bg-green-700 active:bg-green-800 text-white p-3 rounded-full shadow-lg transition-all duration-200 z-10 cursor-pointer group"
              title="Download Image"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
                />
              </svg>
            </button>
          </>
        ) : (
          <p className="text-gray-500 text-sm sm:text-base text-center px-4">
            Your generated image will appear here.
          </p>
        )}
      </div>
    </div>
  );
}
